#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'license_collector'
require_relative 'google_spreadsheet_report'

spreadsheet_id = ENV['LICENSE_REPORT_SPREADSHEET_ID'] || ''

if spreadsheet_id.empty?
  puts 'The LICENSE_REPORT_SPREADSHEET_ID can not be blank!'
  return
end

if ENV['APP_ENV'] == 'development'
  $repo_name = ENV['PROJECT_REPONAME']
  $working_directory = ENV['SCAN_DIR'] + "/#{repository}"
else
  $repo_name = ENV['CIRCLE_PROJECT_REPONAME']
  $working_directory = ENV['CIRCLE_WORKING_DIRECTORY']
end

lc = LicenseCollector.call($working_directory)
worksheet_records = WorksheetReport.new(lc.acknowledged, {}).to_s

GoogleSpreadsheetReport.call($repo_name, worksheet_records)
